import { readFileSync, existsSync, statSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import { marked } from 'marked'

// Notes land here via the obsidian-github-pager plugin's "Base Path" setting,
// which must be configured to exactly "content/notes" to match this script.
const repoRoot = path.resolve(import.meta.dirname, '..')
const notesDir = path.join(repoRoot, 'content/notes')

function findMarkdownFiles(dir) {
  if (!existsSync(dir)) return []
  const files = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findMarkdownFiles(fullPath))
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.md')) {
      files.push(fullPath)
    }
  }
  return files
}

// Defensive fallback only — the plugin already converts [[wikilinks]] and
// ![[embeds]] before pushing, so this just mops up anything that slips through
// (e.g. notes edited/tested locally without going through the plugin).
function stripWikiSyntax(markdown) {
  return markdown
    .replace(/!\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g, '')
    .replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_match, target, alias) => alias ?? target)
}

function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
}

function humanizeFilename(filePath) {
  return path
    .basename(filePath, '.md')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

// The plugin rewrites internal [[note links]] to absolute paths pointing at
// the raw committed file, e.g. /content/notes/Other Note.md — that resolves
// to nothing on the built site, so rewrite it to our real route, /writing/<slug>.
function rewriteInternalNoteLinks(markdown, basenameToSlug) {
  return markdown.replace(/\]\(\/content\/notes\/([^)]+)\.md\)/g, (match, encodedName) => {
    const basename = decodeURIComponent(encodedName)
    const slug = basenameToSlug.get(basename)
    return slug ? `](/writing/${slug})` : match
  })
}

const files = findMarkdownFiles(notesDir)
const parsed = files.map((filePath) => {
  const raw = readFileSync(filePath, 'utf8')
  const { data, content } = matter(raw)
  const title = typeof data.title === 'string' && data.title.trim() ? data.title.trim() : humanizeFilename(filePath)
  const date = data.date ? new Date(data.date) : statSync(filePath).mtime
  return { filePath, title, date, content }
})

const usedSlugs = new Map()
const basenameToSlug = new Map()
for (const note of parsed) {
  let slug = slugify(note.title)
  const count = usedSlugs.get(slug) ?? 0
  usedSlugs.set(slug, count + 1)
  if (count > 0) slug = `${slug}-${count}`
  note.slug = slug
  basenameToSlug.set(path.basename(note.filePath, '.md'), slug)
}

const entries = parsed.map((note) => ({
  slug: note.slug,
  title: note.title,
  date: note.date.toISOString(),
  html: marked.parse(stripWikiSyntax(rewriteInternalNoteLinks(note.content, basenameToSlug))),
}))

entries.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())

const output = `// Generated by scripts/publish-notes.mjs — do not edit by hand.
export type WritingEntry = {
  slug: string
  title: string
  date: string
  html: string
}

export const writing: WritingEntry[] = ${JSON.stringify(entries, null, 2)}
`

writeFileSync(path.join(repoRoot, 'src/data/writing.ts'), output)
console.log(`Published ${entries.length} note${entries.length === 1 ? '' : 's'} to src/data/writing.ts`)
